server:
  port: 8081

spring:
  application:
    name: servicio-productos
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

eureka:
  instance:
    hostname: localhost
