server:
  port: 8082

spring:
  application:
    name: servicio-lista-productos

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Habilitar Feign
spring.cloud.openfeign.client.config.default.connect-timeout: 5000
spring.cloud.openfeign.client.config.default.read-timeout: 5000
